
package com.proyecto.tesisws.interfaces;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSInterface", targetNamespace = "http://interfaces.tesisws.proyecto.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSInterface {


    /**
     * 
     * @param idVehiculo
     * @return
     *     returns java.util.List<com.proyecto.tesisws.interfaces.Destinatarios>
     */
    @WebMethod
    @WebResult(name = "listaDestinatarios", targetNamespace = "")
    @RequestWrapper(localName = "obtenerDestinatariosPorIdVehiculo", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerDestinatariosPorIdVehiculo")
    @ResponseWrapper(localName = "obtenerDestinatariosPorIdVehiculoResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerDestinatariosPorIdVehiculoResponse")
    public List<Destinatarios> obtenerDestinatariosPorIdVehiculo(
        @WebParam(name = "idVehiculo", targetNamespace = "")
        Integer idVehiculo);

    /**
     * 
     * @param idVehiculo
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "exito", targetNamespace = "")
    @RequestWrapper(localName = "enviarMensajeRevisionSensores", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.EnviarMensajeRevisionSensores")
    @ResponseWrapper(localName = "enviarMensajeRevisionSensoresResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.EnviarMensajeRevisionSensoresResponse")
    public boolean enviarMensajeRevisionSensores(
        @WebParam(name = "idVehiculo", targetNamespace = "")
        Integer idVehiculo);

    /**
     * 
     * @return
     *     returns java.util.List<com.proyecto.tesisws.interfaces.Tipovehiculo>
     */
    @WebMethod
    @WebResult(name = "listaTipoVehiculo", targetNamespace = "")
    @RequestWrapper(localName = "obtenerTiposDeVehiculo", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerTiposDeVehiculo")
    @ResponseWrapper(localName = "obtenerTiposDeVehiculoResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerTiposDeVehiculoResponse")
    public List<Tipovehiculo> obtenerTiposDeVehiculo();

    /**
     * 
     * @param destinatario
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "idDestinatario", targetNamespace = "")
    @RequestWrapper(localName = "insertarDestinatario", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.InsertarDestinatario")
    @ResponseWrapper(localName = "insertarDestinatarioResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.InsertarDestinatarioResponse")
    public int insertarDestinatario(
        @WebParam(name = "destinatario", targetNamespace = "")
        Destinatarios destinatario);

    /**
     * 
     * @param usuario
     * @param listaTelefonos
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "exito", targetNamespace = "")
    @RequestWrapper(localName = "actualizarUsuario", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ActualizarUsuario")
    @ResponseWrapper(localName = "actualizarUsuarioResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ActualizarUsuarioResponse")
    public boolean actualizarUsuario(
        @WebParam(name = "usuario", targetNamespace = "")
        Usuarios usuario,
        @WebParam(name = "listaTelefonos", targetNamespace = "")
        List<Telefonos> listaTelefonos);

    /**
     * 
     * @param idUsuario
     * @return
     *     returns java.util.List<com.proyecto.tesisws.interfaces.Telefonos>
     */
    @WebMethod
    @WebResult(name = "listaTelefono", targetNamespace = "")
    @RequestWrapper(localName = "obtenerTelefonosPorIdUsuario", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerTelefonosPorIdUsuario")
    @ResponseWrapper(localName = "obtenerTelefonosPorIdUsuarioResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerTelefonosPorIdUsuarioResponse")
    public List<Telefonos> obtenerTelefonosPorIdUsuario(
        @WebParam(name = "idUsuario", targetNamespace = "")
        Integer idUsuario);

    /**
     * 
     * @param idVehiculo
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "exito", targetNamespace = "")
    @RequestWrapper(localName = "enviarMensajeSuspensionServicio", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.EnviarMensajeSuspensionServicio")
    @ResponseWrapper(localName = "enviarMensajeSuspensionServicioResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.EnviarMensajeSuspensionServicioResponse")
    public boolean enviarMensajeSuspensionServicio(
        @WebParam(name = "idVehiculo", targetNamespace = "")
        Integer idVehiculo);

    /**
     * 
     * @param idVehiculo
     * @param statusInvitacion
     * @param idDestinatario
     * @return
     *     returns com.proyecto.tesisws.interfaces.Vehiculos
     */
    @WebMethod
    @WebResult(name = "vehiculo", targetNamespace = "")
    @RequestWrapper(localName = "aceptarOrechazarInvitacion", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.AceptarOrechazarInvitacion")
    @ResponseWrapper(localName = "aceptarOrechazarInvitacionResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.AceptarOrechazarInvitacionResponse")
    public Vehiculos aceptarOrechazarInvitacion(
        @WebParam(name = "idVehiculo", targetNamespace = "")
        Integer idVehiculo,
        @WebParam(name = "idDestinatario", targetNamespace = "")
        Integer idDestinatario,
        @WebParam(name = "statusInvitacion", targetNamespace = "")
        Integer statusInvitacion);

    /**
     * 
     * @param idVehiculo
     * @param tipoStatus
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "exito", targetNamespace = "")
    @RequestWrapper(localName = "actualizarStatusVehiculo", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ActualizarStatusVehiculo")
    @ResponseWrapper(localName = "actualizarStatusVehiculoResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ActualizarStatusVehiculoResponse")
    public boolean actualizarStatusVehiculo(
        @WebParam(name = "idVehiculo", targetNamespace = "")
        Integer idVehiculo,
        @WebParam(name = "tipoStatus", targetNamespace = "")
        Integer tipoStatus);

    /**
     * 
     * @param idMarca
     * @return
     *     returns java.util.List<com.proyecto.tesisws.interfaces.Modelos>
     */
    @WebMethod
    @WebResult(name = "listaModelos", targetNamespace = "")
    @RequestWrapper(localName = "obtenerModelosPorIdMarca", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerModelosPorIdMarca")
    @ResponseWrapper(localName = "obtenerModelosPorIdMarcaResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerModelosPorIdMarcaResponse")
    public List<Modelos> obtenerModelosPorIdMarca(
        @WebParam(name = "idMarca", targetNamespace = "")
        Integer idMarca);

    /**
     * 
     * @param statusInvitacion
     * @param idDestinatario
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "exito", targetNamespace = "")
    @RequestWrapper(localName = "actualizarStatusInvitacionPorIdDestinatario", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ActualizarStatusInvitacionPorIdDestinatario")
    @ResponseWrapper(localName = "actualizarStatusInvitacionPorIdDestinatarioResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ActualizarStatusInvitacionPorIdDestinatarioResponse")
    public boolean actualizarStatusInvitacionPorIdDestinatario(
        @WebParam(name = "idDestinatario", targetNamespace = "")
        Integer idDestinatario,
        @WebParam(name = "statusInvitacion", targetNamespace = "")
        Integer statusInvitacion);

    /**
     * 
     * @return
     *     returns java.util.List<com.proyecto.tesisws.interfaces.Tipollave>
     */
    @WebMethod
    @WebResult(name = "listaTipoLLave", targetNamespace = "")
    @RequestWrapper(localName = "obtenerTiposDeLLaves", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerTiposDeLLaves")
    @ResponseWrapper(localName = "obtenerTiposDeLLavesResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerTiposDeLLavesResponse")
    public List<Tipollave> obtenerTiposDeLLaves();

    /**
     * 
     * @return
     *     returns java.util.List<com.proyecto.tesisws.interfaces.Marcas>
     */
    @WebMethod
    @WebResult(name = "listaMarcas", targetNamespace = "")
    @RequestWrapper(localName = "obtenerMarcas", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerMarcas")
    @ResponseWrapper(localName = "obtenerMarcasResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerMarcasResponse")
    public List<Marcas> obtenerMarcas();

    /**
     * 
     * @return
     *     returns java.util.List<com.proyecto.tesisws.interfaces.Tipomensaje>
     */
    @WebMethod
    @WebResult(name = "listaTipoMensaje", targetNamespace = "")
    @RequestWrapper(localName = "obtenerTiposDeMensaje", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerTiposDeMensaje")
    @ResponseWrapper(localName = "obtenerTiposDeMensajeResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerTiposDeMensajeResponse")
    public List<Tipomensaje> obtenerTiposDeMensaje();

    /**
     * 
     * @param usuario
     * @return
     *     returns com.proyecto.tesisws.interfaces.Usuarios
     */
    @WebMethod
    @WebResult(name = "Usuario", targetNamespace = "")
    @RequestWrapper(localName = "obtenerUsuario", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerUsuario")
    @ResponseWrapper(localName = "obtenerUsuarioResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerUsuarioResponse")
    public Usuarios obtenerUsuario(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario);

    /**
     * 
     * @param usuario
     * @param telefono
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "idUsuario", targetNamespace = "")
    @RequestWrapper(localName = "registrarUsuario", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.RegistrarUsuario")
    @ResponseWrapper(localName = "registrarUsuarioResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.RegistrarUsuarioResponse")
    public int registrarUsuario(
        @WebParam(name = "usuario", targetNamespace = "")
        Usuarios usuario,
        @WebParam(name = "telefono", targetNamespace = "")
        String telefono);

    /**
     * 
     * @param idVehiculo
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "exito", targetNamespace = "")
    @RequestWrapper(localName = "eliminarVehiculoPorId", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.EliminarVehiculoPorId")
    @ResponseWrapper(localName = "eliminarVehiculoPorIdResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.EliminarVehiculoPorIdResponse")
    public boolean eliminarVehiculoPorId(
        @WebParam(name = "idVehiculo", targetNamespace = "")
        Integer idVehiculo);

    /**
     * 
     * @param telefono
     * @return
     *     returns java.util.List<com.proyecto.tesisws.interfaces.Telefonos>
     */
    @WebMethod
    @WebResult(name = "listaTelefono", targetNamespace = "")
    @RequestWrapper(localName = "buscarTelefonoPorTelefono", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.BuscarTelefonoPorTelefono")
    @ResponseWrapper(localName = "buscarTelefonoPorTelefonoResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.BuscarTelefonoPorTelefonoResponse")
    public List<Telefonos> buscarTelefonoPorTelefono(
        @WebParam(name = "telefono", targetNamespace = "")
        String telefono);

    /**
     * 
     * @param idUsuario
     * @return
     *     returns com.proyecto.tesisws.interfaces.Usuarios
     */
    @WebMethod
    @WebResult(name = "usuario", targetNamespace = "")
    @RequestWrapper(localName = "obtenerUsuarioPorId", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerUsuarioPorId")
    @ResponseWrapper(localName = "obtenerUsuarioPorIdResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerUsuarioPorIdResponse")
    public Usuarios obtenerUsuarioPorId(
        @WebParam(name = "idUsuario", targetNamespace = "")
        Integer idUsuario);

    /**
     * 
     * @param idUsuario
     * @param vehiculoDTO
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "idVehiculo", targetNamespace = "")
    @RequestWrapper(localName = "insertarVehiculo", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.InsertarVehiculo")
    @ResponseWrapper(localName = "insertarVehiculoResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.InsertarVehiculoResponse")
    public int insertarVehiculo(
        @WebParam(name = "vehiculoDTO", targetNamespace = "")
        VehiculoDTO vehiculoDTO,
        @WebParam(name = "idUsuario", targetNamespace = "")
        Integer idUsuario);

    /**
     * 
     * @param idVehiculo
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "exito", targetNamespace = "")
    @RequestWrapper(localName = "eliminarDestinatariosPorIdVehiculo", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.EliminarDestinatariosPorIdVehiculo")
    @ResponseWrapper(localName = "eliminarDestinatariosPorIdVehiculoResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.EliminarDestinatariosPorIdVehiculoResponse")
    public boolean eliminarDestinatariosPorIdVehiculo(
        @WebParam(name = "idVehiculo", targetNamespace = "")
        Integer idVehiculo);

    /**
     * 
     * @param idVehiculo
     * @param idDestinatario
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "exito", targetNamespace = "")
    @RequestWrapper(localName = "enviarInvitacion", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.EnviarInvitacion")
    @ResponseWrapper(localName = "enviarInvitacionResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.EnviarInvitacionResponse")
    public boolean enviarInvitacion(
        @WebParam(name = "idVehiculo", targetNamespace = "")
        Integer idVehiculo,
        @WebParam(name = "idDestinatario", targetNamespace = "")
        Integer idDestinatario);

    /**
     * 
     * @param idDestinatario
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "exito", targetNamespace = "")
    @RequestWrapper(localName = "eliminarDestinatario", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.EliminarDestinatario")
    @ResponseWrapper(localName = "eliminarDestinatarioResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.EliminarDestinatarioResponse")
    public boolean eliminarDestinatario(
        @WebParam(name = "idDestinatario", targetNamespace = "")
        Integer idDestinatario);

    /**
     * 
     * @param idUsuario
     * @param vehiculoDTO
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "exito", targetNamespace = "")
    @RequestWrapper(localName = "actualizarVehiculo", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ActualizarVehiculo")
    @ResponseWrapper(localName = "actualizarVehiculoResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ActualizarVehiculoResponse")
    public boolean actualizarVehiculo(
        @WebParam(name = "vehiculoDTO", targetNamespace = "")
        VehiculoDTO vehiculoDTO,
        @WebParam(name = "idUsuario", targetNamespace = "")
        Integer idUsuario);

    /**
     * 
     * @param idTelefono
     * @return
     *     returns com.proyecto.tesisws.interfaces.Telefonos
     */
    @WebMethod
    @WebResult(name = "Telefono", targetNamespace = "")
    @RequestWrapper(localName = "obtenerTelefonoPorId", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerTelefonoPorId")
    @ResponseWrapper(localName = "obtenerTelefonoPorIdResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerTelefonoPorIdResponse")
    public Telefonos obtenerTelefonoPorId(
        @WebParam(name = "idTelefono", targetNamespace = "")
        Integer idTelefono);

    /**
     * 
     * @param anio
     * @param idVehiculo
     * @param mes
     * @return
     *     returns java.util.List<com.proyecto.tesisws.interfaces.Historicomensajes>
     */
    @WebMethod
    @WebResult(name = "mensajes", targetNamespace = "")
    @RequestWrapper(localName = "obtenerHistoricoPorFecha", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerHistoricoPorFecha")
    @ResponseWrapper(localName = "obtenerHistoricoPorFechaResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerHistoricoPorFechaResponse")
    public List<Historicomensajes> obtenerHistoricoPorFecha(
        @WebParam(name = "idVehiculo", targetNamespace = "")
        Integer idVehiculo,
        @WebParam(name = "mes", targetNamespace = "")
        Integer mes,
        @WebParam(name = "anio", targetNamespace = "")
        Integer anio);

    /**
     * 
     * @param idUsuario
     * @return
     *     returns java.util.List<com.proyecto.tesisws.interfaces.VehiculoDTO>
     */
    @WebMethod
    @WebResult(name = "listaVehiculoDTO", targetNamespace = "")
    @RequestWrapper(localName = "obtenerVehiculosPorIdUsuario", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerVehiculosPorIdUsuario")
    @ResponseWrapper(localName = "obtenerVehiculosPorIdUsuarioResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerVehiculosPorIdUsuarioResponse")
    public List<VehiculoDTO> obtenerVehiculosPorIdUsuario(
        @WebParam(name = "idUsuario", targetNamespace = "")
        Integer idUsuario);

    /**
     * 
     * @param idMarca
     * @return
     *     returns com.proyecto.tesisws.interfaces.Marcas
     */
    @WebMethod
    @WebResult(name = "marca", targetNamespace = "")
    @RequestWrapper(localName = "obtenerMarcaPorId", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerMarcaPorId")
    @ResponseWrapper(localName = "obtenerMarcaPorIdResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerMarcaPorIdResponse")
    public Marcas obtenerMarcaPorId(
        @WebParam(name = "idMarca", targetNamespace = "")
        Integer idMarca);

    /**
     * 
     * @return
     *     returns java.util.List<com.proyecto.tesisws.interfaces.Tipostatus>
     */
    @WebMethod
    @WebResult(name = "listaTipoStatus", targetNamespace = "")
    @RequestWrapper(localName = "obtenerTiposDeStatus", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerTiposDeStatus")
    @ResponseWrapper(localName = "obtenerTiposDeStatusResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerTiposDeStatusResponse")
    public List<Tipostatus> obtenerTiposDeStatus();

    /**
     * 
     * @param idModelo
     * @return
     *     returns com.proyecto.tesisws.interfaces.Modelos
     */
    @WebMethod
    @WebResult(name = "modelo", targetNamespace = "")
    @RequestWrapper(localName = "obtenerModeloPorId", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerModeloPorId")
    @ResponseWrapper(localName = "obtenerModeloPorIdResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerModeloPorIdResponse")
    public Modelos obtenerModeloPorId(
        @WebParam(name = "idModelo", targetNamespace = "")
        Integer idModelo);

    /**
     * 
     * @param destinatario
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "exito", targetNamespace = "")
    @RequestWrapper(localName = "actualizarDestinatario", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ActualizarDestinatario")
    @ResponseWrapper(localName = "actualizarDestinatarioResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ActualizarDestinatarioResponse")
    public boolean actualizarDestinatario(
        @WebParam(name = "destinatario", targetNamespace = "")
        Destinatarios destinatario);

    /**
     * 
     * @param idVehiculo
     * @return
     *     returns java.util.List<com.proyecto.tesisws.interfaces.Llaves>
     */
    @WebMethod
    @WebResult(name = "listaLlaves", targetNamespace = "")
    @RequestWrapper(localName = "obtenerLlaverPorIdVehiculo", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerLlaverPorIdVehiculo")
    @ResponseWrapper(localName = "obtenerLlaverPorIdVehiculoResponse", targetNamespace = "http://interfaces.tesisws.proyecto.com/", className = "com.proyecto.tesisws.interfaces.ObtenerLlaverPorIdVehiculoResponse")
    public List<Llaves> obtenerLlaverPorIdVehiculo(
        @WebParam(name = "idVehiculo", targetNamespace = "")
        Integer idVehiculo);

}
